ci: only support running interface tests from our side currently
That is, drop the code that was intended to support calling or
dispatching the interface-tests workflow from charm repos -- we'll do
that with a separately versioned workflow somewhere else.

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -14,25 +14,26 @@ jobs:
   fast-lint:
     uses: ./.github/workflows/fast-lint.yaml
 
-  get-packages:
+  init:
     runs-on: ubuntu-latest
     outputs:
-      packages: ${{ steps.packages.outputs.packages }}
+      packages: ${{ steps.packages.outputs.result }}
+      interfaces: ${{ steps.interfaces.outputs.result }}
     steps:
       - uses: actions/checkout@v4
         with:
           fetch-depth: 0
-
-      - name: Install uv
-        uses: astral-sh/setup-uv@v6
-
+      - uses: astral-sh/setup-uv@v6
       - name: Collect changed packages
         id: packages
-        run: uv run --no-project --script .github/get-packages.py ${{ github.event.pull_request.base.sha }}
+        run: .github/get-changed.py packages ${{ github.event.pull_request.base.sha }}
+      - name: Collect changed interfaces
+        id: interfaces
+        run: .github/get-changed.py interfaces ${{ github.event.pull_request.base.sha }}
 
   tests:
-    needs: [fast-lint, get-packages]
-    if: ${{ needs.get-packages.outputs.packages != '[]' }}
+    needs: [fast-lint, init]
+    if: ${{ needs.init.outputs.packages != '[]' }}
     strategy:
       fail-fast: false
       matrix:
@@ -46,7 +47,30 @@ jobs:
     if: ${{ !cancelled() }}  # run even if tests are skipped or failed
     runs-on: ubuntu-latest
     steps:
-      - if: ${{ needs.tests.result != 'success' && needs.tests.result != 'skipped' }}
+      - name: Fail if any tests failed
+        if: ${{ needs.tests.result != 'success' && needs.tests.result != 'skipped' }}
+        run: |
+          echo '${{ toJSON(needs) }}'
+          exit 1
+
+  interface-tests:
+    needs: [fast-lint, init]
+    if: ${{ needs.init.outputs.interfaces != '[]' }}
+    strategy:
+      fail-fast: false
+      matrix:
+        interface: ${{ fromJson(needs.get-packages.outputs.interfaces) }}
+    uses: ./.github/workflows/interface-tests.yaml
+    with:
+      interface: ${{ matrix.interface }}
+
+  interface-tests-passed:
+    needs: [interface-tests]
+    if: ${{ !cancelled() }}  # run even if tests are skipped or failed
+    runs-on: ubuntu-latest
+    steps:
+      - name: Fail if any tests failed
+        if: ${{ needs.interface-tests.result != 'success' && needs.interface-tests.result != 'skipped' }}
         run: |
           echo '${{ toJSON(needs) }}'
           exit 1
