ci: collect 0 tests without failing job

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -67,12 +67,14 @@ jobs:
         run: |
           substrates=()
           for substrate in k8s machine; do
+            set +e  # allow this command to fail
             uvx --from rust-just just integration-$substrate ${{ inputs.package }} --collect-only -q
             case $? in
                 0) substrates+=($substrate);;
                 5) echo "No tests for $substrate";;
                 *) echo "Unexpected exit code $?"; exit 1;;
             esac
+            set -e  # make failed commands fatal again
           done
           js=$(jq '$ARGS.positional' --null-input --compact-output --args "${substrates[@]}")
           echo "substrates=$js"
